- name: check "nomad_download_url" variable
  tags: always
  assert:
    that:
      - nomad_download_url is defined
      - nomad_download_url is string
      - nomad_download_url | length
    quiet: true

- name: check if "{{ nomad_download_url }}" is online
  become: false
  run_once: true
  delegate_to: localhost
  uri:
    url: "{{ nomad_download_url }}"
    status_code: 200
  register: _result
  retries: "3"
  delay: "5"
  until: _result.status == 200

- name: check "nomad_version" variable
  tags: always
  assert:
    that:
      - nomad_version is defined
      - nomad_version is string
      - nomad_version | length
    quiet: true

- name: check "nomad_dirs" variable
  tags: always
  assert:
    that:
      - nomad_dirs is defined
      - nomad_dirs is mapping
      - nomad_dirs | length
    quiet: true

- name: check "nomad_config" variable
  tags: always
  assert:
    that:
      - nomad_config is defined
      - nomad_config is mapping
      - nomad_config | length
    quiet: true

- name: check "nomad_configs" variable
  tags: always
  assert:
    that:
      - nomad_configs is defined
      - nomad_configs is mapping
    quiet: true

- name: check "nomad_unit" variable
  tags: always
  assert:
    that:
      - nomad_unit is defined
      - nomad_unit is string
      - nomad_unit | length
    quiet: true

- name: set checksum for {{ _arch }} architecture
  set_fact:
    _archive_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  when:
    - "('linux_' + _arch + '.zip') in item"
