- name: register present configs
  tags: config
  find:
    paths: "{{ nomad_dirs.configs.path }}"
    exclude: "*_vault.json"
    recurse: true
  register: _configs_present

- name: copy configs
  tags: config
  copy:
    content: "{{ config.value | to_nice_json }}"
    dest: "{{ nomad_dirs.configs.path }}/{{ config.key }}.json"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0640
    validate: "nomad config validate {{ nomad_dirs.main.path }}/nomad.json %s"
  notify: restart nomad
  loop: "{{ nomad_configs | dict2items }}"
  loop_control:
    loop_var: "config"
    label: "{{ config.key }}"
  register: _configs_copied

- name: delete configs
  tags: config
  vars:
    _present: "{{ _configs_present | json_query('files[*].path') | default([]) }}"
    _copied: "{{ _configs_copied | json_query('results[*].dest') | default([]) }}"
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ _present | difference(_copied) }}"
  notify: restart nomad
