- name: Preflight
  tags: always
  include_tasks: 00-preflight.yml

- name: Install and configure nomad
  tags: config
  include_tasks: 01-install.yml

- name: Add configs
  tags: config
  include_tasks: 02-configs.yml
